package com.dev.exceptions;

public class ExceptionHandling {

	public static void main(String[] args)throws CustomException {
		/*try {
			s();
		} catch (Exception e) {
			System.out.println("Exception occured.");
			e.printStackTrace();
		}finally {
			System.out.println("This is finally block.");
		}
        System.out.println("Code after Exception");*/
		s();
		try {
			divide(10,0);
		} catch (Exception e) {
			throw new CustomException();
		}	
	}
	public static void s() {
		
		try {
			StringBuffer sb=new StringBuffer(-1);
		} catch (Exception e) {
			// TODO: handle exception
			new CustomException().printStackTrace();
		}
	}
	public static int divide(int i ,int j) {
		int res=i/j;
		System.out.println(res);
		return res;
	}

}
